version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

install:
- ps: >-
    cd src

    nuget restore SharpWindows.sln

    $env:VORTICE_BUILD_NUMBER = ([int]$env:APPVEYOR_BUILD_NUMBER).ToString("000")
   
    $env:BUILD_VERSION_SUFFIX = "pre$env:VORTICE_BUILD_NUMBER"

    $env:appveyor_nuget_push = 'false'
    
    if(-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      if($env:appveyor_repo_tag -eq 'True') {
    	  if($env:appveyor_repo_tag_name -match '^v[0-9]') {
           $env:appveyor_nuget_push = 'true'
           $env:BUILD_VERSION_SUFFIX = ""
        }
    	  if($env:appveyor_repo_tag_name -eq 'latest') {
           $env:appveyor_nuget_push = 'true'
        }        
      }
    }
build:
  project: src/SharpWindows.sln
  verbosity: minimal
before_package:
- cmd: msbuild /t:pack /p:VersionSuffix="%BUILD_VERSION_SUFFIX%" /p:Configuration=Release SharpDXGI/SharpDXGI.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%BUILD_VERSION_SUFFIX%" /p:Configuration=Release SharpDirect3D11/SharpDirect3D11.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%BUILD_VERSION_SUFFIX%" /p:Configuration=Release SharpDirect3D12/SharpDirect3D12.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%BUILD_VERSION_SUFFIX%" /p:Configuration=Release SharpDirect2D/SharpDirect2D.csproj

artifacts:
- path: bin\Release\Packages\*.nupkg
  name: Nugets Artifacts

deploy:
- provider: NuGet
  server: https://www.myget.org/F/vortice/api/v2/package
  api_key:
    secure: rVfu/HYGH96xeQfy+gRBC/ovHCheQKTjwIeNIE9HlpkN6e4/YtPUqn5f036pSlmi
  skip_symbols: false
  symbol_server: https://www.myget.org/F/vortice/api/v2/package
  artifact: Nugets Artifacts
